/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_martin_opencv4android_OpenCVHelper */

#ifndef _Included_com_martin_opencv4android_OpenCVHelper
#define _Included_com_martin_opencv4android_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_martin_opencv4android_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_martin_opencv4android_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_martin_opencv4android_OpenCVHelper
 * Method:    detectFeatures
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_martin_opencv4android_OpenCVHelper_detectFeatures
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
